### ISSUE TITLE
Error on neoudeler.py

### ISSUE THREAD

**Issue by 11ange** [Taipoon/NeoUdeler#4] opened 2023-08-14 15:44 UTC
Greetings!
I'm getting this error running main.py:

Login...
Traceback (most recent call last):
  File "C:\temp\NeoUdeler\main.py", line 58, in <module>
    main()
  File "C:\temp\NeoUdeler\main.py", line 30, in main
    downloader = UdemyDownloader()
                 ^^^^^^^^^^^^^^^^^
  File "C:\temp\NeoUdeler\neoudeler.py", line 533, in __init__
    self._login_udemy()
  File "C:\temp\NeoUdeler\neoudeler.py", line 560, in _login_udemy
    check_response(response_post)
  File "C:\temp\NeoUdeler\neoudeler.py", line 44, in check_response
    raise NeoUdelerError(f'Error with status code: {response.status_code} at {response.url}')
neoudeler.NeoUdelerError: Error with status code: 403 at https://kaishi-pu.udemy.com/join/login-popup/?next=organization/home

Have filled out .env file with correct sub domain, email and password.
Python version is 3.11.4

Thank you!

**Comment by 11ange** [comment] 2023-08-14 20:02
It is getting your business url (kaishi-pu) and not the business indicated in the env file

**Comment by Taipoon** [comment] 2023-08-15 10:25
@11ange 
Hi! 

At the initial startup, I intended to retrieve the subdomain information from the .env file to obtain the access token, but it seems that the hard-coded URL that was in place during the development stage was still left in.

The cause of your error has already been fixed in the main branch.
Please retrieve the latest codebase with the following command.
```shell
git pull origin main
```
Thank you for your report.

**Comment by 11ange** [comment] 2023-08-15 12:11
@Taipoon Working perfectly, thank you!

**Comment by Taipoon** [comment] 2023-08-15 12:15
@11ange 
Thank you, too! I appreciate your cooperation.

**Closed as completed** 2023-08-16 08:02 UTC
Labels: bug
